# username|ssh-key

schaller|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKlDOWuud3RekUucm4eNxapp0Y9oqohTRHvB/4d+rn6A z10n@noexos
eval|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGrSzwPD9dq7Z10/MmKB/HWGObftj02F9FsdKN5QqLUG lecturer@insy-eval
atdit|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINHZednl51u8ckEOrI8pEZiyf17SkAuHVeBb89ZfbLVv atdit@archtop
